# Generated by Django 3.1.8 on 2021-06-23 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('videoID', models.IntegerField()),
                ('initial_comment', models.TextField(max_length=500)),
            ],
        ),
    ]
