# Generated by Django 3.1.8 on 2021-06-24 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('commentID', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('videoID', models.CharField(max_length=50)),
                ('initial_comment', models.TextField(max_length=500)),
                ('likes', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='SubComment',
            fields=[
                ('sub_commentID', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('sub_comment', models.TextField(max_length=500)),
                ('likes', models.IntegerField(default=0)),
                ('commentID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='youtube_clone_server.comments')),
            ],
        ),
    ]
