# Generated by Django 3.1.8 on 2021-06-23 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('youtube_clone_server', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='commentID',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comments',
            name='videoID',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='SubComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_commentID', models.CharField(max_length=50)),
                ('sub_comment', models.TextField(max_length=500)),
                ('commentID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='youtube_clone_server.comments')),
            ],
        ),
    ]
