# Generated by Django 3.1.8 on 2021-06-24 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube_clone_server', '0002_auto_20210623_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subcomment',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
